# 构建并推送镜像
name: github ci

on: push
defaults:
  run:
    shell: bash

jobs:
  build-and-push:

    runs-on: ubuntu-latest
    env:
      token: ${{secrets.DOCKERHUB_TOKEN}}
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: buildah bud -t docker.io/chenxizhan1995/openssl:latest
      - name: push last
        run: buildah push --creds=chenxizhan1995:$token docker.io/chenxizhan1995/openssl:latest
      - name: push version
        run: |
          ver=${GITHUB_REF#refs/tags/v}
          podman tag docker.io/chenxizhan1995/openssl:latest docker.io/chenxizhan1995/openssl:$ver
          buildah push --creds=chenxizhan1995:$token docker.io/chenxizhan1995/openssl:$ver
